# Copyright 2021 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: bmsv1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bmsv1
  template:
    metadata:
      labels:
        app: bmsv1
    spec:
      volumes:
        - name: google-cloud-key
          secret:
            secretName: pubsub-logging-key
      containers:
      - name: bms-app
        # Replace $LOCATION with your Artifact Registry location (e.g., us-west1).
        # Replace $GCLOUD_PROJECT with your project ID.
        image: us-west1-docker.pkg.dev/greenfielddemos/svpassets/bms:v3
        # This app listens on port 8080 for web traffic by default.
        volumeMounts:
          - name: google-cloud-key
            mountPath: /var/secrets/google
        ports:
        - containerPort: 8080
        # Replace Environment Variables to reflect your env values (e.g.,cloud_region to us-west1).
        env:
          - name: PORT
            value: "8080"
          - name: GOOGLE_APPLICATION_CREDENTIALS
            value: /var/secrets/google/key.json
          - name: project_number
            value: 779370283097
          - name: cloud_region
            value: "us-central1"
          - name: subscription_id
            value: "initializeBatteryReqSub"
          - name: subscription_power_id
            value: "batteryPowerReqSub"
          - name: power_allocate_status_topic_id
            value: "svp.simulation.battery.status"
          - name: timeout
            value: 90
          - name: regional
            value: "True"
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
            ephemeral-storage: "1Gi"
          limits:
            memory: "1Gi"
            cpu: "500m"
            ephemeral-storage: "1Gi"
